---
title       : Slidify
subtitle    : Stock Comparison App
author      : Eric Pei
job         : learning about the world
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap, quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
github:
        user: Drontier
        repo: StockSlid
        
---

## What is my App

This is the Stock Comparison App

---
## How do I use the App?

You pick two stocks you want to compare and the time frame you want to compare them against each other. 

The App will graph both stocks next to each other in the same frame.

---
## Why is this useful?

You get the stocks side by side to compare!

You can see the price trajectories of two different stocks. 

Maybe you have regrets about buying Apple over Google.

Maybe you suspect Oil in the last few years is linked to Gold.

This may help you decide which stock you prefer or if certain stocks are positively or negatively correlated.

---

## What other idea did you have for the App?

I think it would be cool to calculate a per year % growth in the comparison to assign a "winner" to the comparisons. 

We aren't always looking just to find a winner. Sometimes we are looking for correlation and this is much more difficult to accomplish within an App.

--- &radio

## Thanks for looking!

Do you like this App?

1. _Yes! =D_

2. No

*** .hint
Click Yes!

*** .explanation
Come on....
---






